# Generated by Django 2.0.1 on 2018-02-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
