# Generated by Django 2.0.1 on 2018-02-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180227_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='check_in_type',
            new_name='checkin_type',
        ),
    ]
